### PR TITLE
Improve tests

### PR DESCRIPTION
**Pull request by AdamWRichardson**
Simple PR to add features of pytest into the python tests which hopefully help readability, performance and coverage.

Happy to have comments and suggestions! I wasn't convinced by the changes in the `cli_test.py` module so happy to change that if required

### CODE REVIEW

**Comment by AdamWRichardson** [comment]
One extra suggestion I have is that we use [tox](https://tox.wiki/en/latest/) to do the python testing, that way it tests the packaging side as well and can simplify running CI. Happy to set it up if you agree

**Comment by AdamWRichardson** [comment]
The CI failing is very strange to me - I cannot seem to re-create the windows failure locally and the MacOS failure doesn't tell me anything on GitHub Actions. If you have any ideas let me know

**Comment by oscarhiggott** [comment]
Hi @AdamWRichardson thank you very much for the contribution! I would be happy to merge your initial refactor of the tests (up to [ab96a79](https://github.com/oscarhiggott/PyMatching/pull/58/commits/ab96a7956a2cbfe866d1494de61ca984a9c2d20a)). It's not yet clear to me whether or not it's worth using tox. For example, we need to test all the different python versions and platforms anyway when building the wheels with cibuildwheels in the CI. Given these need to stay, what advantages does tox offer?

**Comment by AdamWRichardson** [comment]
Thank you! The cibuildwheels is essentially doing the same thing as tox. I was going to say one advantage of tox is that you run the tests on the wheels or sdists that you've built but cibuildwheels also does that. Another advantage tox would give in this case is to be able to specify all build dependencies (cmake, ninja, stim) in one place but keeping commit [dd855d9](https://github.com/oscarhiggott/PyMatching/pull/58/commits/dd855d90132a9dd4110446c53a11de14d48b4d44) would also achieve the same thing.

One actual advantage I've found of tox is that it's usually really easy to reproduce CI commands locally (ironically I can't find why the path is so long on Windows). It means you can run all checks locally before pushing as well so then the only thing you have to worry about is different python versions and OSs.

Perfectly happy to keep using cibuildwheels if you would prefer. I think it would be good to still apply the commit mentioned above to support PEP517/8 backends (I was going to do that in another PR but makes sense to do it here instead)

**Comment by oscarhiggott** [comment]
Thanks! I'd be happy to keep the pyproject.toml changes in [dd855d9](https://github.com/oscarhiggott/PyMatching/pull/58/commits/dd855d90132a9dd4110446c53a11de14d48b4d44) once the CI passes for it. I'm not yet sold on tox as it's not yet clear to me if it offers enough advantages over what cibuildwheels already does (e.g. will it still build each wheel in parallel on a separate worker? This significantly speeds up the workflow.). So I'd suggest leaving tox out of this PR for now, and potentially opening a separate PR for it if you're confident it would be a significant improvement (but I obviously can't promise I'd merge it until I see it).

**Comment by oscarhiggott** [comment]
Thanks, looks great! It would be great if you could add type hints for the test arguments and fixture and then I'd be happy to merge.

**Pull request merged**
