### PR TITLE
Refactor repo structure

### PR DESCRIPTION
**Pull request by AdamWRichardson**
Making this as a draft PR to allow for comments and questions. There's also a problem with the build, I think I dropped a `-fPIC` at some point so will fix that if I can see where it's coming from. Also you might hate this refactor which is completely fine, happy to drop it!

Large structural changes involved are:
* Creation of an `apps` directory which stores the binaries output from pymatching (happy to rename this to `bin` or anything similar)
* Creation of an `include` directory which stores all of the headers
* Abstraction of some of the libraries (which is reflected in `src` and `include`
* Conditionally building the python package (There's probably better conditions we can add to this, maybe a `-DBUILD_PYTHON` which we can add in the `setup.py` file)

I hope these changes make the code a little more extensible and modular. In the future if there's separable logic that can have it's own library (own directory in `src`) then this facilitates that and decouples the code. It should also improve build times overall since it has a proper dependency graph and can compile once link many as required.

Thanks so much Oscar for all the work on this!

### CODE REVIEW

**Comment by Strilanc** [comment]
I don't like moving the headers into include/ and tests into test/. Subjectively speaking, I don't like you're taking files that are strongly related and putting them far apart so I can't as easily key between them in clion. Slightly less subjectively, the [google style guide is to put headers next to source](https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes). Also, it's creating a huge diff that's obscuring the actual changes.

One issue that grouping the files solves is the cmakelist file having to say every file. cmake unfortunately has much worse file globbing than bazel, so you can't just say "match this pattern but not that one". In stim the workaround was to use file lists and a script to regenerate the list and a CI check that the file list was up to date.

**Comment by AdamWRichardson** [comment]
Hi Craig, thanks for the feedback. The refactoring here mostly follows other CMake projects I've made and worked on which uses this sort of structure as in [this example](https://cliutils.gitlab.io/modern-cmake/chapters/basics/structure.html). I didn't consider the google style guide explicitly but had it in the back of my mind. I'm assuming the relevant sentence from the link was 

> All of a project's header files should be listed as descendants of the project's source directory without use of UNIX directory aliases . (the current directory) or .. (the parent directory). 

But that only seems to say that the paths in the include string shouldn't include `.` or `..` not necessarily saying where the header should be. Sorry if I've missed the relevant part of the style guide but I couldn't find a sentence explicitly saying include directories should be avoided. I don't use CLion so can't comment on that.

I personally don't find the globbing problem too difficult, once it's done once it doesn't take much maintenance and is less error prone than a glob. I agree though that whilst the glob support of CMake is there it's not the most helpful.

Just to clarify that the only changes I really wanted to add here *is* this refactor, other changes such as removing the pybind submodule is purely a consequence of that.

**Comment by Strilanc** [comment]
I was referring to this line. I guess it's more of a suggestion line than a requirement:

> dir/foo.cc and dir2/foo2.h are usually in the same directory (e.g., base/basictypes_test.cc and base/basictypes.h), but may sometimes be in different directories too.

I can at least confirm that internally the .h is in fact usually next to the .cc

**Comment by oscarhiggott** [comment]
Hi Adam, many thanks for your work on this. While it would be nice to improve build times/extensibility/modularity, I do also have the same subjective preference as Craig for having the related .cc/.h/.perf.cc/.test.cc files next to each other for ease of access in an IDE, so I'd prefer to leave that structure intact if possible. Are there any changes you'd still propose making without this aspect of the refactor?

**Pull request closed without merging**
